-- Master Wilayah gets two descriptive columns used by Rate Publish and Cek Ongkir's ETA:
--  pulau      : the island group of the province (Jawa, Sumatera, Kalimantan, Sulawesi, Bali, Nusa Tenggara, Maluku, Papua)
--  jarak_jawa : distance class of a LUAR JAWA region from Java - SEDANG or JAUH (NULL for Java itself).
-- JAUH = every Papua province, Maluku and Nusa Tenggara Timur (province-average published lead time of 10+ days in the
-- Harga Publish data); every other Luar Jawa province is SEDANG. Cek Ongkir reads jarak_jawa for the 7-12 / 14-25 day ETA.
ALTER TABLE price_regions ADD COLUMN pulau TEXT;
ALTER TABLE price_regions ADD COLUMN jarak_jawa TEXT CHECK (jarak_jawa IN ('SEDANG','JAUH'));
UPDATE price_regions SET pulau = CASE provinsi WHEN 'DKI Jakarta' THEN 'Jawa' WHEN 'Banten' THEN 'Jawa' WHEN 'Jawa Barat' THEN 'Jawa' WHEN 'Jawa Tengah' THEN 'Jawa' WHEN 'DI Yogyakarta' THEN 'Jawa' WHEN 'Jawa Timur' THEN 'Jawa' WHEN 'Aceh' THEN 'Sumatera' WHEN 'Sumatera Utara' THEN 'Sumatera' WHEN 'Sumatera Barat' THEN 'Sumatera' WHEN 'Riau' THEN 'Sumatera' WHEN 'Kepulauan Riau' THEN 'Sumatera' WHEN 'Jambi' THEN 'Sumatera' WHEN 'Sumatera Selatan' THEN 'Sumatera' WHEN 'Kepulauan Bangka Belitung' THEN 'Sumatera' WHEN 'Bengkulu' THEN 'Sumatera' WHEN 'Lampung' THEN 'Sumatera' WHEN 'Kalimantan Barat' THEN 'Kalimantan' WHEN 'Kalimantan Tengah' THEN 'Kalimantan' WHEN 'Kalimantan Selatan' THEN 'Kalimantan' WHEN 'Kalimantan Timur' THEN 'Kalimantan' WHEN 'Kalimantan Utara' THEN 'Kalimantan' WHEN 'Sulawesi Utara' THEN 'Sulawesi' WHEN 'Sulawesi Tengah' THEN 'Sulawesi' WHEN 'Sulawesi Selatan' THEN 'Sulawesi' WHEN 'Sulawesi Tenggara' THEN 'Sulawesi' WHEN 'Sulawesi Barat' THEN 'Sulawesi' WHEN 'Gorontalo' THEN 'Sulawesi' WHEN 'Bali' THEN 'Bali' WHEN 'Nusa Tenggara Barat' THEN 'Nusa Tenggara' WHEN 'Nusa Tenggara Timur' THEN 'Nusa Tenggara' WHEN 'Maluku' THEN 'Maluku' WHEN 'Maluku Utara' THEN 'Maluku' WHEN 'Papua Kota' THEN 'Papua' WHEN 'Papua Barat' THEN 'Papua' WHEN 'Papua Barat Daya (Sorong)' THEN 'Papua' WHEN 'Papua Selatan (Merauke)' THEN 'Papua' WHEN 'Papua Tengah (Nabire/Timika)' THEN 'Papua' WHEN 'Papua Pegunungan (Wamena)' THEN 'Papua' END;
UPDATE price_regions SET jarak_jawa = CASE provinsi WHEN 'Aceh' THEN 'SEDANG' WHEN 'Sumatera Utara' THEN 'SEDANG' WHEN 'Sumatera Barat' THEN 'SEDANG' WHEN 'Riau' THEN 'SEDANG' WHEN 'Kepulauan Riau' THEN 'SEDANG' WHEN 'Jambi' THEN 'SEDANG' WHEN 'Sumatera Selatan' THEN 'SEDANG' WHEN 'Kepulauan Bangka Belitung' THEN 'SEDANG' WHEN 'Bengkulu' THEN 'SEDANG' WHEN 'Lampung' THEN 'SEDANG' WHEN 'Kalimantan Barat' THEN 'SEDANG' WHEN 'Kalimantan Tengah' THEN 'SEDANG' WHEN 'Kalimantan Selatan' THEN 'SEDANG' WHEN 'Kalimantan Timur' THEN 'SEDANG' WHEN 'Kalimantan Utara' THEN 'SEDANG' WHEN 'Sulawesi Utara' THEN 'SEDANG' WHEN 'Sulawesi Tengah' THEN 'SEDANG' WHEN 'Sulawesi Selatan' THEN 'SEDANG' WHEN 'Sulawesi Tenggara' THEN 'SEDANG' WHEN 'Sulawesi Barat' THEN 'SEDANG' WHEN 'Gorontalo' THEN 'SEDANG' WHEN 'Bali' THEN 'SEDANG' WHEN 'Nusa Tenggara Barat' THEN 'SEDANG' WHEN 'Nusa Tenggara Timur' THEN 'JAUH' WHEN 'Maluku' THEN 'JAUH' WHEN 'Maluku Utara' THEN 'SEDANG' WHEN 'Papua Kota' THEN 'JAUH' WHEN 'Papua Barat' THEN 'JAUH' WHEN 'Papua Barat Daya (Sorong)' THEN 'JAUH' WHEN 'Papua Selatan (Merauke)' THEN 'JAUH' WHEN 'Papua Tengah (Nabire/Timika)' THEN 'JAUH' WHEN 'Papua Pegunungan (Wamena)' THEN 'JAUH' END;
